mindmap
  root((Responsable 
  de 
  Formation))
    Dit
      Dit["J’ai besoin de suivre les compétences des apprenants."]
      Dit["Il faut organiser les modules et les compétences par niveaux."]
      
    Fait
      Fait["Il organise les formations avec des modules et des compétences."]
      Fait["Il cherche des outils pour mieux gérer et suivre les compétences."]

    Besoin
      Besoin["Un tableau pour voir facilement les modules et les progrès des apprenants."]
      Besoin["Un outil pour organiser les compétences avec des explications simples."]
    
    Ressent
      Besoin["Il est parfois stressé par toutes les informations à gérer."]
      Besoin["Il veut une méthode plus facile et plus claire pour suivre les compétences."]

