mindmap
  root((Apprenant))
    Dit
      Dit["Je veux savoir où j’en suis dans mes projets."]
      Dit["Je veux changer facilement l’état de mes projets."]
      
    Fait
      Fait["Il travaille sur ses projets et les envoie pour qu’un formateur les vérifie."]
      Fait["Il regarde son tableau pour voir ses progrès et trouver de l’aide."]

    Besoin
      Besoin["Un endroit simple pour voir ses compétences et l'état de ses projets."]
      Besoin["Un accès facile à des ressources pour l’aider et des retours réguliers des formateurs."]
    
    Ressent
      Besoin["Parfois il ne comprend pas bien comment suivre ses compétences."]
      Besoin["Il est motivé, mais il a besoin de savoir où il en est dans son apprentissage."]
